name: PNH of Hartford
favicon: null
layout_spectrum: 0.08243123278953135
typography_spectrum: 0.44239681866019964
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.18478775955736637
  lightness: 0.7760670757852495
  saturation: 0.4489038640167564
  rhythmicContrast: 0.8501328444108367
purpose: []
