name: PNH of Hartford
favicon: null
layout_spectrum: 0.63699
typography_spectrum: 0.44239681866019964
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#c41230'
    - '#ffffff'
    - '#d2ccb8'
    - '#c6434e'
    - '#c96e6b'
  brandStrength: 0.5
  lightness: 0.5625
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
